'use client';

import { useState, useEffect } from 'react';
import { Sparkles, MapPin, List, Info, AlertOctagon } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';

/**
 * AiTravelPlanner Component
 * 
 * Fetches and displays a personalized travel plan generated by an AI assistant.
 * Rendered after the main dashboard content on the trip dashboard page.
 * 
 * Safety Features:
 * - Isolated logic for fetching and rendering.
 * - Handles loading and error states gracefully.
 * - Responsive layout following the project's design.
 */
export default function AiTravelPlanner({ initialData }: { initialData: any }) {
    const [loading, setLoading] = useState(false);
    const [aiPlan, setAiPlan] = useState<any>(null);
    const [error, setError] = useState<string | null>(null);

    const fetchAiPlan = async () => {
        setLoading(true);
        setError(null);

        try {
            const response = await fetch('/api/ai-travel-plan', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(initialData),
            });

            const data = await response.json();
            if (data.success) {
                setAiPlan(data.plan);
            } else {
                setError(data.error || "Failed to generate AI plan");
            }
        } catch (err: any) {
            console.error("Fetch Error:", err);
            setError("Connection error. Could not reach the planner Service.");
        } finally {
            setLoading(false);
        }
    };

    // Auto-fetch AI plan on load if we have data
    useEffect(() => {
        if (initialData) {
            fetchAiPlan();
        }
    }, [initialData]);

    return (
        <div className="mt-8 border-t border-white/5 pt-12">
            <div className="text-center mb-10">
                <div className="inline-flex items-center gap-2 px-3 py-1 bg-blue-500/10 border border-blue-500/20 rounded-full text-blue-400 text-xs font-bold uppercase tracking-widest shadow-[0_0_15px_rgba(79,140,255,0.1)] mb-4">
                    <Sparkles className="w-3.5 h-3.5" />
                    AI POWERED ENHANCEMENT
                </div>
                <h2 className="text-2xl sm:text-3xl font-bold text-white mb-2">
                    Personalized AI Travel Guide ✨
                </h2>
                <p className="text-white/40 max-w-lg mx-auto text-sm sm:text-base">
                    Based on your preferences, our AI has curated a roadmap for your journey.
                </p>
            </div>

            <AnimatePresence mode="wait">
                {loading ? (
                    <motion.div 
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 1 }}
                        className="flex flex-col items-center justify-center py-20 gap-4"
                    >
                        <div className="w-10 h-10 border-2 border-blue-500 border-t-white rounded-full animate-spin shadow-[0_0_15px_rgba(79,140,255,0.2)]" />
                        <span className="text-white/40 text-sm font-bold tracking-[2px] animate-pulse uppercase">Thinking... 🤔</span>
                    </motion.div>
                ) : error ? (
                    <motion.div 
                        initial={{ opacity: 0, y: 10 }}
                        animate={{ opacity: 1, y: 0 }}
                        className="p-8 rounded-3xl bg-red-900/10 border border-red-500/20 text-center max-w-2xl mx-auto"
                    >
                        <AlertOctagon className="w-12 h-12 text-red-400 mx-auto mb-4" />
                        <h3 className="text-xl font-bold text-white mb-2">Something went wrong</h3>
                        <p className="text-red-400/80 mb-6">{error}</p>
                        <button 
                            onClick={fetchAiPlan} 
                            className="px-6 py-3 rounded-xl bg-white text-black font-bold hover:bg-blue-50 transition-colors active:scale-95"
                        >
                            Try Again
                        </button>
                    </motion.div>
                ) : aiPlan ? (
                    <motion.div 
                        initial={{ opacity: 0, scale: 0.98 }}
                        animate={{ opacity: 1, scale: 1 }}
                        className="grid grid-cols-1 lg:grid-cols-2 gap-8 max-w-7xl mx-auto"
                    >
                        {/* Summary & Itinerary */}
                        <div className="space-y-6">
                            <div className="rounded-3xl border border-white/10 bg-[#161616] p-6 sm:p-8 hover:border-blue-500/30 transition-all group overflow-hidden relative shadow-2xl">
                                <div className="absolute top-0 right-0 p-4 opacity-5 pointer-events-none group-hover:scale-110 transition-transform">
                                    <MapPin className="w-32 h-32" />
                                </div>
                                <h3 className="text-2xl font-bold text-white mb-4 flex items-center gap-3">
                                    <List className="w-6 h-6 text-blue-500" />
                                    {aiPlan.title || 'Your Personalized Plan'}
                                </h3>
                                <p className="text-white/60 leading-relaxed mb-6 italic">
                                    "{aiPlan.summary || 'Enjoy a tailor-made roadmap for your journey.'}"
                                </p>
                                
                                <div className="space-y-4 max-h-[400px] overflow-y-auto pr-2 custom-scrollbar">
                                    {aiPlan.itinerary && aiPlan.itinerary.map((item: any, idx: number) => (
                                        <div key={idx} className="flex gap-4 group">
                                            <div className="flex flex-col items-center gap-1 shrink-0 mt-1">
                                                <div className="w-6 h-6 rounded-full bg-blue-500 text-black text-[10px] font-black flex items-center justify-center">
                                                    {item.day || idx + 1}
                                                </div>
                                                <div className="w-[2px] grow bg-white/10" />
                                            </div>
                                            <div className="pb-6">
                                                <p className="text-white font-medium mb-1 group-hover:text-blue-400 transition-colors">
                                                    {item.activity || 'Activity planned'}
                                                </p>
                                            </div>
                                        </div>
                                    ))}
                                </div>
                            </div>
                        </div>

                        {/* Tips & More */}
                        <div className="space-y-6">
                            <div className="rounded-3xl border border-white/10 bg-[#161616] p-6 sm:p-8 hover:border-pink-500/30 transition-all shadow-2xl">
                                <h3 className="text-2xl font-bold text-white mb-6 flex items-center gap-3">
                                    <Info className="w-6 h-6 text-pink-500" />
                                    Travel Tips 💡
                                </h3>
                                <div className="space-y-4 text-white/50 text-sm sm:text-base leading-relaxed">
                                    {typeof aiPlan.tips === 'string' ? (
                                        <p>{aiPlan.tips}</p>
                                    ) : Array.isArray(aiPlan.tips) ? (
                                        <ul className="list-disc pl-5 space-y-2">
                                            {aiPlan.tips.map((tip: string, i: number) => <li key={i}>{tip}</li>)}
                                        </ul>
                                    ) : (
                                        <p>Be sure to check local weather and prepare for an amazing journey!</p>
                                    )}
                                </div>
                                
                                <div className="mt-8 p-4 rounded-2xl bg-white/5 border border-white/10 text-[11px] uppercase font-bold tracking-[3px] text-white/30 text-center animate-pulse">
                                    AI generated roadmap • Beta v0.9
                                </div>
                            </div>
                        </div>
                    </motion.div>
                ) : (
                    <div className="text-center py-20 text-white/20 italic">
                        Processing your journey details...
                    </div>
                )}
            </AnimatePresence>
        </div>
    );
}
